development:
  adapter: sqlite3
  database: db/sample2_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/sample2_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/sample2.sqlite3
  pool: 5
  timeout: 5000
