development:
  adapter: sqlite3
  database: db/sample_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/sample_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/sample.sqlite3
  pool: 5
  timeout: 5000
